### ISSUE TITLE
Is it possible to combine Instant NeRF with Mobile NeRF?

### ISSUE THREAD

**Issue by floodsung** [google-research/jax3d#110]
If so, the result would be crazy!

**Comment by taiya** [comment]
Yes, of course.
We didn't do it mostly because the PSNR of the scenes would be a tad lower (bad for publishing).

**Comment by kim-jinuk** [comment]
See [https://github.com/kim-jinuk/hash_mobilenerf.git](url)

**Comment by taiya** [comment]
Have a project page?

**Comment by kim-jinuk** [comment]
I wrote the wrong link, please check the link above again.
