### ISSUE TITLE
trained model do not live up to expectations

### ISSUE THREAD

**Issue by CCOSerika** [google-research/jax3d#111]
Hi, author. Thanks so much for your releasing the code!
I tested it on RTX3090 and the result was just excellent.
But when it comes to my real dataset, the trained model looks not as good as the previous.
![0](https://user-images.githubusercontent.com/105965634/185883194-41c41cfd-f9dc-48ba-b141-0ad3a4cb1468.png)
Where lies the problem? Increasing the training_iters or other methods to solve it?

**Comment by taiya** [comment]
which model? which data? how to reproduce?
Also, if it's on real data the issue might be bad camera poses (and they are not refined in this codebase).

**Comment by CCOSerika** [comment]
I generate camera pose file by colmap. And I found the inconsistent pose parameters lead to the suboptimal result.
Is there a way to transform it into what needed?

**Comment by taiya** [comment]
Then it seems your problem is camera calibration, not NeRF training?
Add something to simplify COLMAP's life in the background, or use
a NeRF variant that includes camera calibration (BARF, NeRF--, ...)?

**Comment by CCOSerika** [comment]
The camera pose generated by colmap is accurate, cause I tested it with instant-ngp, and the result is awesome.
Meanwhile, I generate camera pose on nerf_synthetic dataset by colmap, and the result  is obviously inferior to what it should be.
So I guess the problem lies in different format of rotation matrix between what nerf_synthetic dataset comes with and colmap.

**Comment by CCOSerika** [comment]
Hi, taiya. I've solved the problem and the result is satisfactory.
Thanx for ur releasing the code generously and patient response.

**Comment by CCOSerika** [comment]
> 
> Hi @CCOSerika, so how did you solve the issue shown in the image? I may encounter similar issues:)

I use the LLFF dataset instead of NeRF_synthetic for the result of the former format seems to be better.
Meanwhile, improving the image quality and definition works well.
