### ISSUE TITLE
Problem about flax.optim in MobileNerf

### ISSUE THREAD

**Issue by AuthorityWang** [google-research/jax3d#116]
When I try to train the mobilenerf model, I find a problem about `flax`. When I following the guide to install all the lib and trying to run `stage1.py`, it will give an error `module 'flax' has no attribute 'optim'`for line 1476 `state=flax.optim.Adam(**adam_kwargs).create(model_vars)`. I find out that flax I installed is version0.6.0, but an older version like 0.5.3 will be ok. So maybe the `requirements` should make a change? 
Thanks :)

**Comment by czq142857** [comment]
Thanks for bringing this up!
Yes, optim has been removed in the latest flax package.
Please use flax<0.6.0.
