### ISSUE TITLE
[MobileNeRF] About the HTML of real360

### ISSUE THREAD

**Issue by mdarhdarz** [google-research/jax3d#125]
I tried a custom real360 scene, and the render functions in python code can render the images in all the stages. However, when using the html, I only got the fragments of mesh. How can I solve this problem? Thanks a lot!
![0](https://user-images.githubusercontent.com/84657631/191735514-7628fbc5-0f3e-47dd-9287-457d44114539.png)

**Comment by cyz2727327** [comment]
Hi, are you able to run real360 scene? I am struggling to even start stage1 for it, may I ask your machine config and package version please?
