### ISSUE TITLE
Provide Pre-Trained NeRF Checkpoints

### ISSUE THREAD

**Issue by vorasaurus** [google-research/jax3d#136]
Provide Pre-trained NeRF Checkpoints that can be used for training NeSF semantic module.

**Comment by duckworthd** [comment]
NeRF checkpoints are now online. I uploaded one tar file per dataset. Each tar file contains 3 elements per scene,

*`scene_<scene_id>.density_grid`: an numpy array stored with `np.save`. Contains precomputed values corresponding to NeRF model density at even points along a grid.
* `scene_<scene_id>.params`: a JSON file configuring the NeRF model.
* `scene_<scene_id>.variables/`: a folder containing a NeRF model checkpoint.

https://pantheon.corp.google.com/storage/browser/kubric-public/data/NeSFDatasets/NeRF%20checkpoints
