### ISSUE TITLE
Will subjective results on datasets be published?

### ISSUE THREAD

**Issue by Jiangxg** [google-research/jax3d#175]
Hello, congratulations on your wonderful work.
I am going to cite your paper and compare my method to your work mobileNeRF subjectively.
So, I am wondering that are you planning to publish the results on Synthetic 360 and Forward Facing?
Thank you!

**Comment by czq142857** [comment]
The dataset is not ours. They are from Mipnerf360 and they have already been released. See https://jonbarron.info/mipnerf360

**Comment by Jiangxg** [comment]
Sorry, but I mean the rendered images in test views :）
